### PR TITLE
Added Easy Crypto to Fiat On/Off Ramps

### PR DESCRIPTION
**Pull request by alangrainger**
Added https://easycrypto.ai/ to Fiat On/Off Ramps for Australia, New Zealand, and South Africa.

### CODE REVIEW

**Comment by ghettodev** [comment]
Hi Alan,

This is a repo for Makerdao related tooling and apps. I'm not seeing dai or mkr in your app. Am I looking in the wrong place?

**Comment by alangrainger** [comment]
Hi Richard - we're a fiat on/off ramp :) People use us to convert fiat to DAI and vice versa.

You can find DAI on our Rates page here: https://easycrypto.ai/nz/rates

It's one of our most popular stablecoins!

**Comment by ghettodev** [comment]
That's strange. I looked through your entire site carefully not more than 7 hours ago and there was no reference to dai anywhere...

I just attempted to convert 5 NZD to dai and it displays this message "Due to low DAI liquidity we recommend placing a smaller order. The quoted amount is not guaranteed." 

Where do you source liquidity?

**Comment by alangrainger** [comment]
Currently we're having an issue with Kraken so we're stuck with Bittrex for the moment. It's fine for orders up to $5,000, but higher than that I would expect some slippage. Normally we source from Kraken.

**Comment by alangrainger** [comment]
For reference, we listed DAI on 9 Oct 2019.

**Comment by alangrainger** [comment]
Hi @ghettodev - anything else I can provide for you for this one?

**Comment by ghettodev** [comment]
looks good. thanks alan.

**Pull request merged**
